import type { CefrLevel, EnglishLesson, EnglishPrompt, EnglishQuestionBank } from "./types";

export const ENGLISH_BANK_VERSION="cefr-core-2026.1";
export const ENGLISH_LEVEL_KEY="personal-workspace-cefr-level";
export const cefrLevels:CefrLevel[]=["A1","A2","B1","B2","C1"];
export const cefrDescriptions:Record<CefrLevel,string>={A1:"入门：生活中的基础词句",A2:"初级：熟悉场景与简单交流",B1:"中级：独立表达经历与想法",B2:"中高级：清楚讨论抽象主题",C1:"高级：准确、自然地深入表达"};

type LevelPool={words:EnglishPrompt[];sentences:EnglishPrompt[];shadowing:EnglishPrompt[];speaking:EnglishPrompt[];listening:EnglishPrompt[]};
const p=(text:string,translation:string):EnglishPrompt=>({text,translation});
const pools:Record<CefrLevel,LevelPool>={
 A1:{
  words:[p("hello","你好"),p("family","家人"),p("water","水"),p("morning","早晨"),p("happy","开心的"),p("friend","朋友"),p("home","家"),p("work","工作"),p("learn","学习"),p("today","今天"),p("food","食物"),p("walk","走路"),p("book","书"),p("music","音乐"),p("sleep","睡觉"),p("help","帮助"),p("small","小的"),p("good","好的"),p("time","时间"),p("please","请")],
  sentences:[p("Good morning. How are you?","早上好，你好吗？"),p("I drink water every day.","我每天喝水。"),p("This is my favorite book.","这是我最喜欢的书。"),p("I am happy to see you.","很高兴见到你。"),p("Please help me, thank you.","请帮帮我，谢谢。"),p("I walk home after work.","我下班后走路回家。"),p("What time is it?","现在几点？"),p("I like music and coffee.","我喜欢音乐和咖啡。"),p("My family is at home.","我的家人在家。"),p("I want to learn English.","我想学习英语。")],
  shadowing:[p("I start my day with a glass of water.","我用一杯水开始新的一天。"),p("Today is a good day to learn something new.","今天是学习新事物的好日子。"),p("I can do one small thing at a time.","我可以一次做好一件小事。"),p("My friend and I walk home together.","我和朋友一起走路回家。")],
  speaking:[p("Introduce yourself in three simple sentences.","用三个简单句介绍自己。"),p("Talk about your morning routine.","说说你的早晨习惯。"),p("Describe your favorite food.","描述你最喜欢的食物。"),p("Talk about one person in your family.","介绍一位家人。")],
  listening:[p("Listen and identify five words about daily life.","听一段慢速日常英语，找出五个生活词汇。"),p("Listen for names, times, and places.","听辨人名、时间和地点。"),p("Listen to a greeting and repeat it twice.","听一句问候并重复两次。"),p("Listen to a short order at a café.","听一段咖啡店点单。")]
 },
 A2:{
  words:[p("appointment","预约"),p("available","有空的"),p("choose","选择"),p("decide","决定"),p("direction","方向"),p("exercise","运动"),p("favorite","最喜欢的"),p("healthy","健康的"),p("invite","邀请"),p("message","消息"),p("prepare","准备"),p("remember","记得"),p("schedule","日程"),p("travel","旅行"),p("weather","天气"),p("weekend","周末"),p("practice","练习"),p("usually","通常"),p("different","不同的"),p("important","重要的")],
  sentences:[p("Are you available this weekend?","你这周末有空吗？"),p("I usually exercise after work.","我通常下班后运动。"),p("Could you send me the address?","你能把地址发给我吗？"),p("I need to prepare for tomorrow.","我需要为明天做准备。"),p("The weather is different today.","今天天气不一样。"),p("Let us choose a time together.","我们一起选个时间吧。"),p("I forgot to reply to your message.","我忘记回复你的消息了。"),p("This habit is important to me.","这个习惯对我很重要。"),p("How do I get to the station?","我怎么去车站？"),p("I enjoyed my trip last month.","我很享受上个月的旅行。")],
  shadowing:[p("I checked my schedule and chose a better time.","我查看日程并选择了更合适的时间。"),p("Regular practice helps me remember new expressions.","规律练习帮助我记住新表达。"),p("The weather changed, so we prepared a different plan.","天气变了，所以我们准备了不同的计划。"),p("I try to make healthy choices during the week.","工作日我尽量做健康的选择。")],
  speaking:[p("Describe your plans for the weekend.","描述你的周末计划。"),p("Explain how to get from your home to a station.","说明从家到车站的路线。"),p("Talk about a healthy habit you practice.","介绍一个你坚持的健康习惯。"),p("Invite a friend to do something together.","邀请朋友一起做一件事。")],
  listening:[p("Listen to a weather forecast and note two details.","听天气预报并记下两个细节。"),p("Listen to directions and draw the route.","听路线说明并画出路线。"),p("Listen to a phone message and note the appointment time.","听电话留言并记下预约时间。"),p("Listen to two people planning a weekend.","听两个人安排周末。")]
 },
 B1:{
  words:[p("achieve","达成"),p("challenge","挑战"),p("confident","自信的"),p("experience","经历"),p("improve","改善"),p("opinion","观点"),p("opportunity","机会"),p("progress","进步"),p("recommend","推荐"),p("responsible","负责的"),p("solution","解决方案"),p("support","支持"),p("balance","平衡"),p("communicate","沟通"),p("effective","有效的"),p("environment","环境"),p("manage","管理"),p("purpose","目的"),p("reflect","反思"),p("result","结果")],
  sentences:[p("I learned a lot from that experience.","我从那次经历中学到很多。"),p("In my opinion, the plan is practical.","在我看来，这个计划很实际。"),p("The biggest challenge was managing my time.","最大的挑战是管理时间。"),p("I would recommend this method to beginners.","我会向初学者推荐这个方法。"),p("We need a solution that works for everyone.","我们需要一个适合所有人的方案。"),p("I feel more confident than I did last year.","我比去年更自信。"),p("Good communication can prevent problems.","良好沟通可以预防问题。"),p("I am responsible for the final result.","我对最终结果负责。"),p("This opportunity helped me make progress.","这个机会帮助我取得进步。"),p("It is important to balance work and rest.","平衡工作和休息很重要。")],
  shadowing:[p("Reflecting on my experience helps me make better decisions.","反思经历能帮助我做出更好的决定。"),p("Clear communication is often the most effective solution.","清晰沟通往往是最有效的解决方案。"),p("Progress becomes visible when we practice with a clear purpose.","带着明确目的练习，进步就会显现。"),p("A difficult challenge can become a valuable opportunity.","困难的挑战可以变成宝贵机会。")],
  speaking:[p("Describe a challenge you overcame.","描述一次你克服的挑战。"),p("Give your opinion about working from home.","谈谈你对居家工作的看法。"),p("Recommend a useful learning method.","推荐一种有效的学习方法。"),p("Explain how you balance work and rest.","说明你如何平衡工作与休息。")],
  listening:[p("Listen to a personal story and summarize the turning point.","听个人故事并总结转折点。"),p("Listen to an opinion and list two supporting reasons.","听一个观点并列出两个理由。"),p("Listen to a workplace problem and identify the solution.","听职场问题并找出解决方案。"),p("Listen for the speaker's attitude and conclusion.","听辨说话者态度与结论。")]
 },
 B2:{
  words:[p("approach","方法"),p("assumption","假设"),p("consequence","后果"),p("consistent","持续一致的"),p("crucial","关键的"),p("evaluate","评估"),p("evidence","证据"),p("flexible","灵活的"),p("impact","影响"),p("insight","洞察"),p("perspective","视角"),p("priority","优先事项"),p("reliable","可靠的"),p("significant","显著的"),p("strategy","策略"),p("adapt","适应"),p("clarify","澄清"),p("complex","复杂的"),p("efficient","高效的"),p("maintain","维持")],
  sentences:[p("We should evaluate the evidence before deciding.","决定前应评估证据。"),p("This approach could have a significant impact.","这个方法可能产生显著影响。"),p("From another perspective, the result is encouraging.","换个角度看，结果令人鼓舞。"),p("Consistency is crucial for long-term progress.","持续一致对长期进步至关重要。"),p("We need a flexible strategy for a complex situation.","复杂情境需要灵活策略。"),p("Could you clarify the assumption behind your argument?","你能澄清论点背后的假设吗？"),p("The source appears reliable, but we need more evidence.","来源似乎可靠，但仍需更多证据。"),p("We adapted our priorities after reviewing the data.","审查数据后，我们调整了优先级。"),p("The immediate benefit may not outweigh the consequence.","眼前收益未必大于后果。"),p("An efficient system should also be easy to maintain.","高效系统也应易于维护。")],
  shadowing:[p("A reliable conclusion depends on evidence rather than assumption.","可靠结论依赖证据而非假设。"),p("The most efficient approach is not always the most sustainable one.","最高效的方法不一定最可持续。"),p("Considering several perspectives can reveal valuable insights.","考虑多个视角能带来有价值的洞察。"),p("A flexible strategy allows a team to adapt without losing focus.","灵活策略让团队在不失焦的情况下适应变化。")],
  speaking:[p("Evaluate the benefits and risks of remote work.","评估远程工作的利弊。"),p("Defend a strategy for improving productivity.","为提升效率的策略进行论证。"),p("Compare two perspectives on social media.","比较对社交媒体的两种观点。"),p("Explain a decision using evidence and consequences.","用证据和后果解释一个决定。")],
  listening:[p("Listen to a debate and map each speaker's argument.","听辩论并整理双方论点。"),p("Listen to a report and distinguish fact from opinion.","听报告并区分事实与观点。"),p("Listen for hedging language and degrees of certainty.","听辨缓和语和确信程度。"),p("Summarize a five-minute interview in three points.","用三点总结五分钟访谈。")]
 },
 C1:{
  words:[p("ambiguous","模棱两可的"),p("coherent","连贯的"),p("compelling","有说服力的"),p("conventional","传统的"),p("dilemma","困境"),p("distinction","区别"),p("elaborate","详细阐述"),p("framework","框架"),p("implication","潜在影响"),p("inherent","内在的"),p("nuance","细微差别"),p("paradox","悖论"),p("plausible","看似合理的"),p("preliminary","初步的"),p("scrutinize","仔细审视"),p("subsequent","随后的"),p("subtle","微妙的"),p("sustainable","可持续的"),p("underlying","根本的"),p("viable","可行的")],
  sentences:[p("The preliminary findings warrant closer scrutiny.","初步发现值得进一步审视。"),p("Her argument is coherent, although one assumption remains ambiguous.","她的论点连贯，但一个假设仍不明确。"),p("The distinction is subtle yet highly significant.","这种区别微妙却很重要。"),p("We need a viable framework for sustainable growth.","我们需要可持续增长的可行框架。"),p("The policy has implications that extend beyond its immediate purpose.","该政策的影响超出其直接目的。"),p("What appears paradoxical may reflect an underlying tension.","看似悖论的现象可能反映深层张力。"),p("The explanation is plausible but not entirely compelling.","这个解释看似合理，但并非完全有说服力。"),p("Could you elaborate on the nuance you mentioned?","你能详细说明刚才提到的细微差别吗？"),p("The subsequent analysis challenged the conventional view.","后续分析挑战了传统观点。"),p("Every model has inherent limitations.","每个模型都有内在局限。")],
  shadowing:[p("A compelling argument acknowledges uncertainty without becoming ambiguous.","有说服力的论证承认不确定性，但不会含糊不清。"),p("The underlying dilemma cannot be resolved within a purely conventional framework.","根本困境无法在纯传统框架内解决。"),p("Subtle distinctions often carry significant practical implications.","细微区别往往带来重要的实际影响。"),p("A viable long-term strategy must be both coherent and sustainable.","可行的长期策略必须兼具连贯性和可持续性。")],
  speaking:[p("Discuss a modern dilemma from two competing perspectives.","从两个相互竞争的视角讨论现代困境。"),p("Challenge a conventional assumption with a coherent argument.","用连贯论证挑战一个传统假设。"),p("Explain the subtle implications of a recent trend.","解释某个近期趋势的微妙影响。"),p("Present a sustainable framework for long-term learning.","提出长期学习的可持续框架。")],
  listening:[p("Listen to an academic discussion and identify implied assumptions.","听学术讨论并识别隐含假设。"),p("Track how a speaker qualifies and revises a claim.","追踪说话者如何限定并修正主张。"),p("Summarize both explicit arguments and underlying implications.","总结明确论点与潜在影响。"),p("Listen for rhetorical contrast, nuance, and stance.","听辨修辞对比、细微差别与立场。")]
 }
};

const hash=(value:string)=>[...value].reduce((n,c)=>((n<<5)-n+c.charCodeAt(0))|0,2166136261)>>>0;
const take=<T>(items:T[],start:number,count:number)=>Array.from({length:count},(_,i)=>items[(start+i)%items.length]);
export function builtInLesson(date:string,level:CefrLevel):EnglishLesson{
 const pool=pools[level],seed=hash(`${ENGLISH_BANK_VERSION}:${date}:${level}`);
 return {id:`built-in:${level}:${date}`,level,words:take(pool.words,seed%pool.words.length,5),sentences:take(pool.sentences,(seed>>>3)%pool.sentences.length,3),shadowing:pool.shadowing[(seed>>>5)%pool.shadowing.length],speaking:pool.speaking[(seed>>>7)%pool.speaking.length],listening:pool.listening[(seed>>>9)%pool.listening.length]};
}
export function selectLesson(date:string,level:CefrLevel,banks:EnglishQuestionBank[]=[]){const custom=banks.flatMap(bank=>bank.lessons).filter(x=>x.level===level);return custom.length?custom[hash(`${date}:${level}`)%custom.length]:builtInLesson(date,level)}
export function validateQuestionBank(value:unknown):EnglishQuestionBank{const bank=value as Partial<EnglishQuestionBank>;if(!bank||typeof bank.id!=="string"||typeof bank.name!=="string"||typeof bank.version!=="string"||!Array.isArray(bank.lessons)||!bank.lessons.length)throw new Error("题库格式不正确");for(const lesson of bank.lessons){if(!cefrLevels.includes(lesson.level)||!Array.isArray(lesson.words)||lesson.words.length<5||!Array.isArray(lesson.sentences)||lesson.sentences.length<3)throw new Error("题库课程内容不完整")};return {...bank,source:bank.source||"用户导入",importedAt:new Date().toISOString()} as EnglishQuestionBank}
