"use client";
import { useState } from "react";
import { useLiveQuery } from "dexie-react-hooks";
import { CheckCircle2, ChevronLeft, ChevronRight, CircleHelp, ExternalLink, KeyRound, PlugZap, RefreshCw, ShieldCheck, Trash2, XCircle } from "lucide-react";
import { db } from "@/lib/db";
import { deleteAiConnection, providerCatalog, providerDefinition, readSavedKey, saveAiConnection, testAiConnection } from "@/lib/ai-connection";
import type { AiProviderId } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";

export function AiConnectionCenter(){
 const connection=useLiveQuery(()=>db.aiConnections.get("active"),[]);const [open,setOpen]=useState(false),[info,setInfo]=useState(false),[health,setHealth]=useState<{ok:boolean;text:string}|null>(null),[checking,setChecking]=useState(false);
 const [step,setStep]=useState(1),[provider,setProvider]=useState<AiProviderId>("deepseek"),[model,setModel]=useState(""),[baseUrl,setBaseUrl]=useState(""),[apiKey,setApiKey]=useState(""),[help,setHelp]=useState(false),[testing,setTesting]=useState(false),[result,setResult]=useState<{ok:boolean;text:string}|null>(null);
 const definition=providerDefinition(provider);
 const reset=(replace=false)=>{const selected=replace&&connection?providerDefinition(connection.provider):providerDefinition("deepseek");setProvider(selected.id);setModel(replace&&connection?connection.model:selected.model);setBaseUrl(replace&&connection?connection.baseUrl:selected.baseUrl);setApiKey("");setStep(1);setResult(null);setHelp(false);setOpen(true)};
 const choose=(id:AiProviderId)=>{const next=providerDefinition(id);setProvider(id);setModel(next.model);setBaseUrl(next.baseUrl);setResult(null)};
 const test=async()=>{if(!apiKey.trim()||!model.trim()||!baseUrl.trim()){setResult({ok:false,text:"请完整填写 API Key、模型和 API 地址"});return}setTesting(true);setResult(null);try{await testAiConnection({provider,model: model.trim(),baseUrl:baseUrl.trim()},apiKey.trim());setResult({ok:true,text:"已成功接入"})}catch(error){const raw=error instanceof Error?error.message:"连接失败";setResult({ok:false,text:raw.includes("Failed to fetch")?"浏览器无法连接该服务。请检查网络、API 地址或服务商是否允许浏览器请求。":raw})}finally{setTesting(false)}};
 const finish=async()=>{if(!result?.ok)return;await saveAiConnection({provider,model:model.trim(),baseUrl:baseUrl.trim()},apiKey.trim());setApiKey("");setStep(4)};
 const remove=async()=>{if(!confirm("确定删除当前 AI 连接与本机加密密钥？"))return;await deleteAiConnection();setOpen(false)};
 const checkHealth=async()=>{if(!connection)return;setChecking(true);setHealth(null);try{const key=await readSavedKey();if(!key)throw new Error("本机密钥不存在，请重新连接");await testAiConnection(connection,key);setHealth({ok:true,text:"AI 已连接"})}catch(error){setHealth({ok:false,text:error instanceof Error?error.message:"检查失败"})}finally{setChecking(false)}};
 return <><section className="ai-center-card"><header><span className="ai-center-icon"><PlugZap/></span><div><small>设置 · AI 中心</small><h2>AI 状态</h2></div><button className="ai-info" onClick={()=>setInfo(!info)} aria-label="查看 AI 中心说明"><CircleHelp/></button></header><div className={`ai-state ${connection?"connected":"offline"}`}><i/>{connection?<>已连接 {providerDefinition(connection.provider).name}<small>{connection.model}</small></>:<>尚未接入 AI<small>直播助手目前会使用本地规则模式</small></>}</div>{info&&<p className="ai-privacy"><ShieldCheck/>密钥只在当前设备加密保存，不会进入数据导出、GitHub 或任何 Personal Workspace 服务器。调用 AI 时，请求会直接发送给你选择的服务商。</p>}<div className="ai-center-actions"><Button onClick={()=>reset(false)}><KeyRound/>连接 AI</Button><Button variant="outline" onClick={()=>reset(true)} disabled={!connection}><RefreshCw/>更换 AI</Button></div>{connection&&<div className="ai-health"><Button variant="outline" onClick={checkHealth} disabled={checking}>{checking?<><RefreshCw className="animate-spin"/>正在检查</>:"一键检查 AI 是否正常"}</Button><Button variant="ghost" className="text-destructive" onClick={remove}><Trash2/>删除连接</Button>{health&&<p className={health.ok?"success":"error"}>{health.ok?<CheckCircle2/>:<XCircle/>}{health.text}</p>}</div>}</section>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="ai-wizard sm:max-w-2xl"><DialogHeader><DialogTitle>连接 AI</DialogTitle><DialogDescription>一次连接，整个工作台共用。密钥不会上传到 Personal Workspace。</DialogDescription></DialogHeader><div className="wizard-progress">{[1,2,3,4].map(x=><span key={x} className={step>=x?"active":""}><i>{step>x?<CheckCircle2/>:x}</i><b>{["选择 AI","取得 Key","测试连接","完成"][x-1]}</b></span>)}</div>{step===1&&<div className="wizard-page"><h3>选择 AI 服务商</h3><div className="provider-grid">{providerCatalog.map(item=><button key={item.id} className={provider===item.id?"active":""} onClick={()=>choose(item.id)}><i style={{background:item.color}}>{item.mark}</i><b>{item.name}</b>{provider===item.id&&<CheckCircle2/>}</button>)}</div>{provider==="openai-compatible"&&<div className="compatible-fields"><label>API Base URL<Input value={baseUrl} onChange={e=>setBaseUrl(e.target.value)} placeholder="https://example.com/v1"/></label><label>模型名称<Input value={model} onChange={e=>setModel(e.target.value)} placeholder="model-name"/></label></div>}</div>}{step===2&&<div className="wizard-page key-guide"><span className="provider-large" style={{background:definition.color}}>{definition.mark}</span><h3>前往官方取得 API Key</h3>{definition.website?<Button onClick={()=>window.open(definition.website,"_blank","noopener,noreferrer")}><ExternalLink/>打开官方网站</Button>:<p>请前往你的服务商后台取得 API Key。</p>}<button className="help-toggle" onClick={()=>setHelp(!help)}><CircleHelp/>不知道怎么取得？</button>{help&&<ol>{definition.help.map((line,index)=><li key={line}><i>{index+1}</i>{line}</li>)}</ol>}</div>}{step===3&&<div className="wizard-page"><h3>贴上 API Key</h3><label className="secret-field">API Key<Input type="password" autoComplete="off" value={apiKey} onChange={e=>{setApiKey(e.target.value);setResult(null)}} placeholder="只保存在这台设备"/></label>{provider!=="openai-compatible"&&<div className="connection-summary"><span>服务商<b>{definition.name}</b></span><span>模型<b>{model}</b></span></div>}<Button className="test-button" onClick={test} disabled={testing||!apiKey.trim()}>{testing?<><RefreshCw className="animate-spin"/>正在测试</>:<><PlugZap/>测试连接</>}</Button>{result&&<div className={`test-result ${result.ok?"success":"error"}`}>{result.ok?<CheckCircle2/>:<XCircle/>}<span><b>{result.ok?"已成功接入":"连接失败"}</b><small>{result.text}</small></span></div>}</div>}{step===4&&<div className="wizard-page wizard-done"><CheckCircle2/><h3>AI 已连接</h3><div><span>目前 AI<b>{definition.name}</b></span><span>模型<b>{model}</b></span><span>状态<b>正常</b></span></div><Button onClick={()=>setOpen(false)}>完成</Button></div>}<footer>{step>1&&step<4&&<Button variant="ghost" onClick={()=>{setStep(step-1);setResult(null)}}><ChevronLeft/>上一步</Button>}<span/>{step<3&&<Button onClick={()=>setStep(step+1)} disabled={step===1&&(!model||!baseUrl)}>下一步<ChevronRight/></Button>}{step===3&&<Button onClick={finish} disabled={!result?.ok}>保存并继续<ChevronRight/></Button>}</footer></DialogContent></Dialog></>
}
