"use client";

import {useMemo,useState} from "react";
import {useLiveQuery} from "dexie-react-hooks";
import {Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis} from "recharts";
import {Copy,Gift,Heart,PenLine,Plus,Search,Sparkles,Trash2,TrendingUp,Users} from "lucide-react";
import {db} from "@/lib/db";
import {callProvider,readSavedKey} from "@/lib/ai-connection";
import {futureGiftProviders,giftPlatformProvider} from "@/lib/gift-platform-provider";
import {today,uid,type GiftRecord} from "@/lib/types";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";

const money=(value:number)=>`¥${value.toFixed(2)}`;
const nowTime=()=>new Date().toTimeString().slice(0,5);
const empty=()=>({date:today(),time:nowTime(),platform:"B站",room:"",username:"",giftName:"",quantity:1,unitValue:0,notes:"",tags:[] as string[]});
const total=(record:GiftRecord)=>record.quantity*record.unitValue;
const startOfWeek=(date:string)=>{const value=new Date(`${date}T00:00:00`),day=(value.getDay()+6)%7;value.setDate(value.getDate()-day);return value.toLocaleDateString("en-CA")};
const cleanThanks=(text:string)=>text.split("\n").filter(line=>!/^(作为|以下|我建议|当然|根据)/.test(line.trim())).join("\n").trim();
const localThanks=(gift:Pick<GiftRecord,"username"|"giftName"|"quantity">)=>`① 亲切版\n谢谢 ${gift.username} 送来的${gift.quantity}个${gift.giftName}，你的心意我收到啦！\n\n② 高情商版\n感谢 ${gift.username} 的${gift.giftName}，有你支持，今天的直播更有意义。\n\n③ 宠粉版\n${gift.username} 宝宝的${gift.giftName}太暖了，我会把这份偏爱好好记住！`;

export function GiftDashboardCard({open}:{open:()=>void}){const rows=useLiveQuery(()=>db.giftRecords.where("date").equals(today()).toArray(),[])||[],amount=rows.reduce((sum,row)=>sum+total(row),0),users=[...new Set(rows.map(row=>row.username))],top=Object.values(rows.reduce<Record<string,{name:string;amount:number}>>((map,row)=>{map[row.username]??={name:row.username,amount:0};map[row.username].amount+=total(row);return map},{})).sort((a,b)=>b.amount-a.amount)[0];const advice=users.length?`今天有 ${users.length} 位送礼观众，${top?`记得多回应 ${top.name}，`:""}也别忘了欢迎第一次送礼的新朋友。`:"今天还没有礼物记录，直播后可以手动补记。";return <button className="gift-home-card" onClick={open}><span><Gift/><i>今日直播收益</i></span><strong>{money(amount)}</strong><div><small>送礼人数</small><b>{users.length}</b><small>Top 观众</small><b>{top?.name||"暂无"}</b></div><p><Sparkles/>{advice}</p></button>}

export function GiftAssistant(){
 const queried=useLiveQuery(()=>db.giftRecords.orderBy("date").reverse().toArray(),[]),records=useMemo(()=>queried||[],[queried]);
 const connection=useLiveQuery(()=>db.aiConnections.get("active"),[]);
 const [form,setForm]=useState(empty),[editing,setEditing]=useState<string|null>(null),[showForm,setShowForm]=useState(false),[search,setSearch]=useState(""),[platform,setPlatform]=useState("全部"),[sort,setSort]=useState("new"),[thanks,setThanks]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 const todayRows=records.filter(row=>row.date===today()),todayValue=todayRows.reduce((sum,row)=>sum+total(row),0),todayUsers=new Set(todayRows.map(row=>row.username)).size;
 const weekStart=startOfWeek(today()),month=today().slice(0,7),weekValue=records.filter(x=>x.date>=weekStart&&x.date<=today()).reduce((s,x)=>s+total(x),0),monthValue=records.filter(x=>x.date.startsWith(month)).reduce((s,x)=>s+total(x),0),historyValue=records.reduce((s,x)=>s+total(x),0);
 const crm=useMemo(()=>Object.values(records.reduce<Record<string,{username:string;count:number;amount:number;last:string;notes:string;tags:Set<string>}>>((map,row)=>{const key=`${row.platform}:${row.username}`;map[key]??={username:row.username,count:0,amount:0,last:row.date,notes:"",tags:new Set()};map[key].count+=row.quantity;map[key].amount+=total(row);if(row.date>=map[key].last){map[key].last=row.date;map[key].notes=row.notes}row.tags.forEach(tag=>map[key].tags.add(tag));return map},{})).sort((a,b)=>b.amount-a.amount),[records]);
 const topToday=Object.values(todayRows.reduce<Record<string,{name:string;amount:number}>>((map,row)=>{map[row.username]??={name:row.username,amount:0};map[row.username].amount+=total(row);return map},{})).sort((a,b)=>b.amount-a.amount).slice(0,10);
 const trend=useMemo(()=>Object.values(records.reduce<Record<string,{date:string;value:number}>>((map,row)=>{map[row.date]??={date:row.date.slice(5),value:0};map[row.date].value+=total(row);return map},{})).sort((a,b)=>a.date.localeCompare(b.date)).slice(-14),[records]);
 const visible=records.filter(row=>(platform==="全部"||row.platform===platform)&&[row.username,row.giftName,row.room,row.notes].join(" ").toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==="value"?total(b)-total(a):sort==="user"?a.username.localeCompare(b.username,"zh-CN"):`${b.date}${b.time}`.localeCompare(`${a.date}${a.time}`));
 const save=async()=>{if(!form.username.trim()||!form.giftName.trim()){setNotice("请填写用户名称和礼物名称");return}const stamp=new Date().toISOString();const row:GiftRecord={...form,id:editing||uid(),source:"manual",createdAt:editing?records.find(x=>x.id===editing)?.createdAt||stamp:stamp,updatedAt:stamp};await db.giftRecords.put(row);setForm(empty());setEditing(null);setShowForm(false);setNotice("礼物记录已保存")};
 const edit=(row:GiftRecord)=>{setEditing(row.id);setForm({date:row.date,time:row.time,platform:row.platform,room:row.room,username:row.username,giftName:row.giftName,quantity:row.quantity,unitValue:row.unitValue,notes:row.notes,tags:row.tags});setShowForm(true)};
 const generateThanks=async(row:GiftRecord)=>{setBusy(true);setNotice("");try{if(!connection){setThanks(localThanks(row));return}const key=await readSavedKey();if(!key)throw new Error("AI 密钥不可用，请到设置 → AI 中心重新连接");const system="你是直播礼物感谢话术助手。只输出①亲切版、②高情商版、③宠粉版。每条20至45个中文字，可直接在直播间说。禁止解释、分析、前言、结尾和自我介绍。";const prompt=`用户：${row.username}\n礼物：${row.giftName}\n数量：${row.quantity}\n请直接生成三种感谢话术。生成批次：${crypto.randomUUID()}`;setThanks(cleanThanks(await callProvider(connection,key,prompt,500,system,.9)))}catch(error){setNotice(error instanceof Error?error.message:"生成失败")}finally{setBusy(false)}};
 return <div className="gift-page">
  <section className="gift-hero"><div><small>LIVE GIFT ASSISTANT</small><h2>直播礼物助手</h2><p>手动记录现在就能用，平台自动同步接口已经预留。</p></div><Button onClick={()=>{setEditing(null);setForm(empty());setShowForm(!showForm)}}><Plus/>新增礼物</Button></section>
  <div className="gift-metrics"><article><Gift/><span><small>今日礼物总数</small><b>{todayRows.reduce((s,x)=>s+x.quantity,0)}</b></span></article><article><TrendingUp/><span><small>今日礼物价值</small><b>{money(todayValue)}</b></span></article><article><Users/><span><small>今日送礼人数</small><b>{todayUsers}</b></span></article><article><Heart/><span><small>历史累计收入</small><b>{money(historyValue)}</b></span></article></div>
  {showForm&&<section className="gift-form"><header><b>{editing?"编辑礼物记录":"手动新增礼物"}</b><small>当前来源：{giftPlatformProvider.name}</small></header><div>{[["date","日期","date"],["time","时间","time"],["platform","平台","text"],["room","直播间名称","text"],["username","用户名称","text"],["giftName","礼物名称","text"]].map(([key,label,type])=><label key={key}>{label}<Input type={type} value={String(form[key as keyof typeof form])} onChange={event=>setForm({...form,[key]:event.target.value})}/></label>)}<label>数量<Input type="number" min="1" value={form.quantity} onChange={e=>setForm({...form,quantity:Number(e.target.value)})}/></label><label>单个礼物价值<Input type="number" min="0" step="0.01" value={form.unitValue} onChange={e=>setForm({...form,unitValue:Number(e.target.value)})}/></label><label className="wide">标签（逗号分隔）<Input value={form.tags.join(",")} onChange={e=>setForm({...form,tags:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})} placeholder="VIP, 铁粉, 潜力粉丝"/></label><label className="wide">备注<Textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><footer><Button variant="outline" onClick={()=>setShowForm(false)}>取消</Button><Button onClick={save}>保存记录</Button></footer></section>}
  {notice&&<p className="gift-notice" role="status">{notice}</p>}
  <div className="gift-dashboard"><section className="gift-chart"><header><div><b>收礼趋势</b><small>最近 14 个有记录的日期</small></div><div><span>本周 {money(weekValue)}</span><span>本月 {money(monthValue)}</span></div></header><ResponsiveContainer width="100%" height={240}><AreaChart data={trend}><defs><linearGradient id="giftValue" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#168cff" stopOpacity={.45}/><stop offset="95%" stopColor="#168cff" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} opacity={.18}/><XAxis dataKey="date" axisLine={false} tickLine={false}/><Tooltip formatter={value=>money(Number(value))}/><Area type="monotone" dataKey="value" stroke="#0874dc" fill="url(#giftValue)" strokeWidth={3}/></AreaChart></ResponsiveContainer></section><section className="gift-top"><header><b>今日 Top 10</b><small>{todayUsers} 位送礼观众</small></header>{topToday.length?topToday.map((row,index)=><div key={row.name}><i>{index+1}</i><span>{row.name}</span><b>{money(row.amount)}</b></div>):<p>今天还没有礼物记录。</p>}</section></div>
  <section className="gift-records"><header><div><b>礼物记录</b><small>新增、编辑、删除、搜索、筛选与排序</small></div><div className="gift-tools"><label><Search/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索用户、礼物或直播间"/></label><select value={platform} onChange={e=>setPlatform(e.target.value)}><option>全部</option>{[...new Set(records.map(x=>x.platform))].map(x=><option key={x}>{x}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="new">最新优先</option><option value="value">金额最高</option><option value="user">用户名称</option></select></div></header><div className="gift-table">{visible.length?visible.map(row=><article key={row.id}><div><b>{row.giftName} × {row.quantity}</b><small>{row.date} {row.time} · {row.platform} · {row.room||"未填写直播间"}</small></div><span><b>{row.username}</b><small>{row.tags.join(" · ")||"普通观众"}</small></span><strong>{money(total(row))}</strong><div className="gift-row-actions"><button onClick={()=>generateThanks(row)} disabled={busy}><Sparkles/>感谢话术</button><button onClick={()=>edit(row)} aria-label="编辑"><PenLine/></button><button onClick={()=>db.giftRecords.delete(row.id)} aria-label="删除"><Trash2/></button></div></article>):<p className="gift-empty">还没有礼物记录，点击“新增礼物”开始使用。</p>}</div></section>
  {thanks&&<section className="gift-thanks"><header><div><Sparkles/><span><b>感谢话术</b><small>{connection?`由 ${connection.provider} 生成`:"本机规则生成"}</small></span></div><button onClick={()=>navigator.clipboard.writeText(thanks)}><Copy/>一键复制</button></header><pre>{thanks}</pre><button onClick={()=>setThanks("")}>关闭</button></section>}
  <section className="gift-crm"><header><b>送礼用户 CRM</b><small>相同平台与用户名会自动累计</small></header><div>{crm.length?crm.slice(0,20).map((viewer,index)=><article key={viewer.username}><i>{index+1}</i><div><b>{viewer.username}</b><small>最近送礼 {viewer.last}</small></div><span><b>{viewer.count}</b><small>累计数量</small></span><span><b>{money(viewer.amount)}</b><small>累计金额</small></span><em>{[...viewer.tags].join(" · ")||"待添加标签"}</em></article>):<p className="gift-empty">产生礼物记录后，观众资料会自动汇总。</p>}</div></section>
  <section className="gift-providers"><b>未来平台自动同步</b><p>目前仅使用手动记录，未连接任何直播平台。</p><div>{futureGiftProviders.map(item=><span key={item.id}>{item.name}<small>接口已预留</small></span>)}</div></section>
 </div>;
}
