"use client";
/* eslint-disable react-hooks/exhaustive-deps */
import { useMemo, useState, type CSSProperties } from "react";
import { useLiveQuery } from "dexie-react-hooks";
import { Check, CheckCircle2, Copy, Dumbbell, FileText, Heart, Languages, Mic, Radio, RefreshCw, Sparkles, Volume2 } from "lucide-react";
import { db } from "@/lib/db";
import { generateWithConnectedAi } from "@/lib/ai-connection";
import { ensureEnglishDailyPlan, setWorkoutCheckin, toggleEnglishDailyTask, workoutStats } from "@/lib/daily";
import { cefrDescriptions, cefrLevels, ENGLISH_LEVEL_KEY } from "@/lib/english-question-bank";
import { today, uid, type AiToolMode, type CefrLevel } from "@/lib/types";
import { exportAllData, importAllData } from "@/lib/data-portability";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Textarea } from "@/components/ui/textarea";

export function DashboardPhaseTwo(){
 const tasks=useLiveQuery(()=>db.tasks.where("due").equals(today()).toArray(),[])||[];
 const checkins=useLiveQuery(()=>db.workoutCheckins.toArray(),[]); const storedPlan=useLiveQuery(()=>db.englishDailyPlans.get(today()),[]),plan=storedPlan?.source?.startsWith("AI 动态生成")?storedPlan:undefined;
 const notes=useLiveQuery(()=>db.notes.orderBy("updatedAt").reverse().limit(1).toArray(),[])||[];
 const streams=useLiveQuery(()=>db.streams.orderBy("date").reverse().limit(1).toArray(),[])||[];
 const stats=useMemo(()=>workoutStats(checkins||[]),[checkins]); const englishTasks=tasks.filter(x=>x.id.startsWith(`english-daily:${today()}:`));
 const remaining=tasks.filter(x=>!x.done).length,completed=tasks.filter(x=>x.done),progress=tasks.length?Math.round(completed.length/tasks.length*100):0;
 const suggestion=stats.todayDone?(englishTasks.some(x=>!x.done)?"今天英语还没有全部完成，抽出五分钟完成下一项。":remaining?`今天还剩 ${remaining} 项任务，先完成最轻松的一项。`:"今天的目标已经全部完成，可以安心休息了。") : "建议先完成运动打卡，让身体进入状态，再处理第一项任务。";
 return <section className="today-control-center"><header><div><span><Sparkles/>今日 AI 摘要</span><h2>今天的控制中心</h2><p>{remaining?`还有 ${remaining} 项待完成，当前整体进度 ${progress}%。`:"今天的事项已经全部完成。"}</p></div><strong style={{"--progress":`${progress}%`} as CSSProperties}>{progress}%</strong></header><div className="control-metrics"><article><CheckCircle2/><b>今日待完成</b><span>{remaining} 项</span></article><article><Languages/><b>今日英文</b><span>{plan?`${englishTasks.filter(x=>x.done).length}/${plan.items.length}`:"准备中"}</span></article><article><Dumbbell/><b>今日运动</b><span>{stats.todayDone?"已打卡":"未打卡"}</span></article><article><Radio/><b>今日直播</b><span>{streams[0]?.date===today()?streams[0].platform:"暂无记录"}</span></article><article><FileText/><b>最近笔记</b><span>{notes[0]?.title||"暂无笔记"}</span></article><article><Check/><b>最近完成</b><span>{completed[0]?.title||"暂无完成"}</span></article></div><div className="control-next"><Sparkles/><div><b>AI 建议下一步</b><p>{suggestion}</p></div></div></section>
}

const storedLevel=():CefrLevel=>{if(typeof window==="undefined")return "A1";const value=localStorage.getItem(ENGLISH_LEVEL_KEY);return cefrLevels.includes(value as CefrLevel)?value as CefrLevel:"A1"};
const speak=(text:string)=>{if(typeof window==="undefined"||!("speechSynthesis" in window))return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang="en-US";utterance.rate=.88;const voices=window.speechSynthesis.getVoices(),voice=voices.find(x=>x.lang.startsWith("en-US"))||voices.find(x=>x.lang.startsWith("en"));if(voice)utterance.voice=voice;window.speechSynthesis.speak(utterance)};
export function EnglishDailyTasks(){
 const storedPlan=useLiveQuery(()=>db.englishDailyPlans.get(today()),[]),plan=storedPlan?.source?.startsWith("AI 动态生成")?storedPlan:undefined,tasks=useLiveQuery(()=>db.tasks.where("due").equals(today()).toArray(),[])||[],connection=useLiveQuery(()=>db.aiConnections.get("active"),[]);
 const [level,setLevel]=useState<CefrLevel>(storedLevel),[status,setStatus]=useState(""),[busy,setBusy]=useState(false);
 const [needsLevel,setNeedsLevel]=useState(()=>typeof window!=="undefined"&&!localStorage.getItem(ENGLISH_LEVEL_KEY));
 const generate=async(next=level,replace=false)=>{setBusy(true);setStatus("");try{await ensureEnglishDailyPlan(today(),next,replace);setStatus("今日英语已生成并保存到本机") }catch(error){setStatus(error instanceof Error?error.message:"生成失败，请稍后重试")}finally{setBusy(false)}};
 const choose=async(next:CefrLevel)=>{setLevel(next);setNeedsLevel(false);localStorage.setItem(ENGLISH_LEVEL_KEY,next);await generate(next,Boolean(plan))};
 const done=tasks.filter(x=>x.id.startsWith(`english-daily:${today()}:`)&&x.done).length;
 return <section className="phase-panel english-daily"><header><div><b>AI 每日英语</b><p>{plan?.source||"每天首次打开由已连接的 AI 生成，生成后当天固定使用"}</p></div><span>{plan?`${done}/${plan.items.length}`:"待生成"}</span></header><div className={`cefr-picker ${needsLevel?"needs-choice":""}`}><div><b>{needsLevel?"首次使用，请选择英语程度":"我的程度"}</b><small>{cefrDescriptions[level]}</small></div><nav>{cefrLevels.map(x=><button key={x} className={level===x?"active":""} disabled={busy} onClick={()=>choose(x)}>{x}</button>)}</nav></div>{!plan?<div className="english-empty"><Sparkles/><b>{connection?"正在准备今天的英语内容":"尚未连接 AI"}</b><p>{connection?"如未自动生成，可点击下方按钮重试。":"请先到设置 → AI 中心连接服务商。连接后每天只生成一次。"}</p><Button onClick={()=>generate()} disabled={busy||!connection}>{busy?"生成中…":"生成今日英语"}</Button></div>:<div className="english-task-list">{plan.items.map(item=>{const task=tasks.find(x=>x.id===item.taskId);return <article key={item.kind} className={task?.done?"done":""}><Checkbox checked={task?.done||false} onCheckedChange={v=>toggleEnglishDailyTask(item.taskId,Boolean(v))}/><div><b>{item.title}</b>{item.kind==="words"?<div className="word-grid">{item.prompts?.map(word=><section key={word.text}><div><strong>{word.text}</strong><em>{word.phonetic}</em><button onClick={()=>speak(word.text)} aria-label={`播放 ${word.text}`}><Volume2/></button></div><p>{word.translation}</p><small>{word.example}</small><small>{word.exampleTranslation}</small></section>)}</div>:<><small>{item.detail}</small>{item.prompts&&<div className="prompt-chips">{item.prompts.map(prompt=><button key={prompt.text} onClick={()=>speak(prompt.text)} title={`播放：${prompt.text}`}><Volume2/>{prompt.text}</button>)}</div>}</>}</div><button className="speak-all" onClick={()=>speak(item.prompts?.map(x=>x.text).join(". ")||item.detail)} aria-label={`播放${item.title}`}><Volume2/></button>{item.kind==="shadowing"&&<button className="reserved-mic" title="已预留跟读评分接口" disabled><Mic/></button>}</article>})}</div>}{status&&<p className="phase-status">{status}</p>}</section>
}

export function WorkoutCheckinPanel(){const rows=useLiveQuery(()=>db.workoutCheckins.toArray(),[])||[];const stats=useMemo(()=>workoutStats(rows),[rows]);return <section className="phase-panel workout-checkin"><header><div><b>每日运动打卡</b><p>点击即可记录今天的完成状态。</p></div><Button onClick={()=>setWorkoutCheckin(today(),!stats.todayDone)} variant={stats.todayDone?"secondary":"default"}>{stats.todayDone?<><Check/>已打卡</>:"今日打卡"}</Button></header><div className="checkin-stats"><span><b>{stats.streak}</b><small>连续天数</small></span><span><b>{stats.week}</b><small>本周打卡</small></span><span><b>{stats.month}</b><small>本月打卡</small></span></div></section>}

const modes:{id:AiToolMode;label:string;placeholder:string}[]=[{id:"reply",label:"高情商回复",placeholder:"输入观众留言"},{id:"review",label:"直播复盘",placeholder:"输入今天直播的内容、对话和发生的事情"},{id:"coach",label:"话术教练",placeholder:"输入直播间情境，例如：有人嫌贵、冷场、没人留言"}];
const replyStyles=["亲切","幽默","带货","高情商","高价值","宠粉","留人","成交"];
export function StreamAiAssistant(){const [mode,setMode]=useState<AiToolMode>("reply"),[style,setStyle]=useState("高情商"),[input,setInput]=useState(""),[output,setOutput]=useState(""),[recordId,setRecordId]=useState(""),[favorite,setFavorite]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");const connection=useLiveQuery(()=>db.aiConnections.get("active"),[]);const current=modes.find(x=>x.id===mode)!;const run=async(nextStyle=style)=>{if(!input.trim())return;setBusy(true);setNotice("");try{const live=await generateWithConnectedAi(mode,input,nextStyle),id=uid();setOutput(live.output);setRecordId(id);setFavorite(false);await db.aiToolRecords.add({id,mode,input,output:live.output,provider:live.provider,createdAt:new Date().toISOString(),favorite:false,style:nextStyle})}catch(error){setNotice(error instanceof Error?error.message:"生成失败")}finally{setBusy(false)}};const chooseStyle=(next:string)=>{setStyle(next);if(input.trim())void run(next)};const toggleFavorite=async()=>{if(!recordId)return;const next=!favorite;await db.aiToolRecords.update(recordId,{favorite:next});setFavorite(next)};return <section className="phase-panel ai-assistant"><header><div><b>直播 AI 助手</b><p>{connection?`当前使用 ${connection.provider} · ${connection.model}`:"请先到设置 → AI 中心连接 AI"}</p></div></header><nav>{modes.map(x=><button className={mode===x.id?"active":""} onClick={()=>{setMode(x.id);setOutput("")}} key={x.id}>{x.label}</button>)}</nav>{mode==="reply"&&<div className="reply-styles" aria-label="回复风格">{replyStyles.map(x=><button key={x} className={style===x?"active":""} disabled={busy} onClick={()=>chooseStyle(x)}>{x}</button>)}</div>}<Textarea value={input} onChange={e=>setInput(e.target.value)} placeholder={current.placeholder} className="min-h-32"/><div className="phase-actions"><Button onClick={()=>run()} disabled={busy||!input.trim()||!connection}>{busy?"生成中…":"生成内容"}</Button></div>{notice&&<p className="phase-status">{notice}</p>}{output&&<div className="ai-output-card"><div className="ai-output-toolbar"><button onClick={()=>navigator.clipboard.writeText(output)}><Copy/>一键复制</button><button onClick={()=>run()} disabled={busy}><RefreshCw/>重新生成</button><button className={favorite?"active":""} onClick={toggleFavorite}><Heart/> {favorite?"已收藏":"收藏"}</button></div><pre>{output}</pre></div>}</section>}

export async function initializeDailyFeatures(){await ensureEnglishDailyPlan(today(),storedLevel())}

export function CompleteDataPanel(){const [status,setStatus]=useState("");const exportData=async()=>{const data=await exportAllData();const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));const link=document.createElement("a");link.href=url;link.download=`personal-workspace-v3-${today()}.json`;link.click();URL.revokeObjectURL(url);setStatus("完整数据已导出")};const importData=async(e:React.ChangeEvent<HTMLInputElement>)=>{try{const file=e.target.files?.[0];if(!file)return;await importAllData(JSON.parse(await file.text()));setStatus("完整数据已导入")}catch(error){setStatus(error instanceof Error?error.message:"导入失败")}};return <section className="phase-panel"><header><div><b>完整数据管理（v3）</b><p>涵盖原有数据、运动打卡、AI 每日英语计划与直播 AI 历史。</p></div></header><div className="phase-actions"><Button onClick={exportData}>导出完整 JSON</Button><label className="import-button">导入完整 JSON<input type="file" accept="application/json" onChange={importData}/></label></div>{status&&<p className="phase-status">{status}</p>}</section>}
