"use client";
/* eslint-disable @next/next/no-img-element */

import type { ReactNode } from "react";
import { motion } from "motion/react";
import type { LucideIcon } from "lucide-react";
import { ChevronLeft, Coffee, Gamepad2, Leaf, PawPrint, Sparkles, Star } from "lucide-react";
import type { WorkspaceTheme } from "./workspace-theme-provider";

export type PackPage = "dashboard"|"tasks"|"english"|"workouts"|"notes"|"streams"|"contacts"|"settings";
export type PackNavItem = { id:PackPage; label:string; icon:LucideIcon };
type Props = { page:PackPage; title:string; nav:PackNavItem[]; go:(page:PackPage)=>void; children:ReactNode; theme:WorkspaceTheme };

const NavButton=({item,active,go,className=""}:{item:PackNavItem;active:boolean;go:(p:PackPage)=>void;className?:string})=><motion.button whileTap={{scale:.88}} onClick={()=>go(item.id)} className={`${className} ${active?"active":""}`} aria-current={active?"page":undefined}><item.icon/><span>{item.label.replace("每日","")}</span></motion.button>;

export function BunnyLifeShell({page,title,nav,go,children}:Props){return <div className="pack pack-bunny"><div className="bunny-cloud cloud-a"/><div className="bunny-cloud cloud-b"/><header className="bunny-top"><button onClick={()=>go("dashboard")}><img src="/packs/bunny-life.png" alt="兔兔生活助手"/><span><small>今天也一起加油</small><b>{title}</b></span></button><span className="carrot-score">今日能量</span></header><aside className="bunny-path"><div className="garden-title"><Sparkles/><b>Bunny Life</b></div>{nav.map((n,i)=><NavButton key={n.id} item={n} active={page===n.id} go={go} className={`garden-stop stop-${i}`}/>)}</aside><main className="pack-stage bunny-stage">{children}</main><nav className="pack-mobile bunny-mobile">{nav.slice(0,5).map(n=><NavButton key={n.id} item={n} active={page===n.id} go={go}/>)}</nav></div>}

export function CatCafeShell({page,title,nav,go,children}:Props){return <div className="pack pack-cafe"><aside className="cafe-counter"><button className="cafe-brand" onClick={()=>go("dashboard")}><Coffee/><b>Cat Cafe</b><small>OPEN · 今日營業中</small></button><div className="cafe-menu-label">TODAY&apos;S MENU</div>{nav.map(n=><NavButton key={n.id} item={n} active={page===n.id} go={go} className="cafe-menu-item"/>)}<img src="/packs/cat-cafe.png" alt="貓咪咖啡師" className="cafe-mascot"/></aside><header className="cafe-note"><PawPrint/><span><small>店長的手寫便條</small><b>{title}</b></span></header><main className="pack-stage cafe-table">{children}</main><nav className="pack-mobile cafe-tabs">{nav.slice(0,5).map(n=><NavButton key={n.id} item={n} active={page===n.id} go={go}/>)}</nav></div>}

export function PeachBubbleShell({page,title,nav,go,children}:Props){return <div className="pack pack-peach"><div className="bubble-field"><i/><i/><i/><i/></div><header className="peach-header"><button onClick={()=>go("dashboard")}><ChevronLeft/><span><small>Peach Bubble</small><b>{title}</b></span></button><motion.img animate={{y:[0,-7,0],rotate:[-2,2,-2]}} transition={{repeat:Infinity,duration:4}} src="/packs/peach-bubble.png" alt="蜜桃泡泡"/></header><nav className="peach-ribbon">{nav.map(n=><NavButton key={n.id} item={n} active={page===n.id} go={go}/>)}</nav><main className="pack-stage peach-stage">{children}</main><nav className="pack-mobile peach-dock">{nav.slice(0,5).map(n=><NavButton key={n.id} item={n} active={page===n.id} go={go}/>)}</nav></div>}

export function ForestDiaryShell({page,title,nav,go,children}:Props){return <div className="pack pack-forest"><header className="forest-sign"><button onClick={()=>go("dashboard")}><Leaf/><span><small>FOREST DIARY</small><b>{title}</b></span></button></header><aside className="forest-trail"><img src="/packs/forest-diary.png" alt="森林朋友"/><div className="trail-line"/>{nav.map((n,i)=><NavButton key={n.id} item={n} active={page===n.id} go={go} className={`trail-stop trail-${i}`}/>)}</aside><main className="pack-stage forest-cabin">{children}</main><nav className="pack-mobile forest-mobile">{nav.slice(0,5).map(n=><NavButton key={n.id} item={n} active={page===n.id} go={go}/>)}</nav></div>}

export function LittlePlanetShell({page,title,nav,go,children}:Props){return <div className="pack pack-space"><div className="space-stars">{Array.from({length:18},(_,i)=><i key={i}/>)}</div><header className="space-hud"><button onClick={()=>go("dashboard")}><Star/><span><small>LITTLE PLANET</small><b>{title}</b></span></button><img src="/packs/little-planet.png" alt="小星球"/></header><nav className="orbit-nav">{nav.map((n,i)=><NavButton key={n.id} item={n} active={page===n.id} go={go} className={`orbit orbit-${i}`}/>)}</nav><main className="pack-stage planet-stage">{children}</main><nav className="pack-mobile planet-mobile">{nav.slice(0,5).map(n=><NavButton key={n.id} item={n} active={page===n.id} go={go}/>)}</nav></div>}

export function PetAssistantShell({page,title,nav,go,children}:Props){return <div className="pack pack-game"><header className="game-hud"><button onClick={()=>go("dashboard")}><Gamepad2/><span><small>LV. 01 · DAILY QUEST</small><b>{title}</b></span></button><div className="game-bars"><span>ENERGY</span><i><b/></i></div></header><aside className="game-menu"><img src="/packs/pet-assistant.png" alt="寵物助手夥伴"/><div className="pet-status"><b>夥伴心情</b><span>開心跳躍中</span></div>{nav.map(n=><NavButton key={n.id} item={n} active={page===n.id} go={go} className="quest-button"/>)}</aside><main className="pack-stage game-stage">{children}</main><nav className="pack-mobile game-mobile">{nav.slice(0,5).map(n=><NavButton key={n.id} item={n} active={page===n.id} go={go}/>)}</nav></div>}

export const packShells:Record<WorkspaceTheme,(props:Props)=>ReactNode>={"bunny-life":BunnyLifeShell,"cat-cafe":CatCafeShell,"peach-bubble":PeachBubbleShell,"forest-diary":ForestDiaryShell,"little-planet":LittlePlanetShell,"pet-assistant":PetAssistantShell};
